### ISSUE TITLE
Table of Symbols: What is 8-bit gray level? How important is the size?

### ISSUE THREAD

**Issue by balacij** [joedf/CAS741_w23#9]
Since you're dealing with images in your program, I think it's fairly reasonable that you would have some “implementation-level” details in your SRS (since how else would you discuss images?). However, I _think_ you might want to address it a bit since you're discussing the “quality” of the images in your case study. Specifically, you might want to address:
* what is the importance of the size?
* how does the input image encodings relate to your mathematics?
* how will you represent the images internally in your program once they've been read in? (Since I imagine how you represent the images will affect the math involved with your instance models?)

Assuming these are important, you might also need to tie them back to your instance models, or perhaps add them as system constraints.

**Comment by joedf** [comment]
@balacij @smiths 
Could the 8 [bit-depth](https://en.wikipedia.org/wiki/Color_depth) be an assumption? Since I dont want to make the problem more complex having to deal with different ones. In electron microscopy (EM), it can be common to go to 16 bit-depth, but generally everywhere we post images on the web or even in journals or articles, they tend to get reduced to 8 bit-depth...

Or should leave it as is? Since in EM, this can be important when looking at samples that have a wide range of elements that produce low intensity like carbon with high intensity elements like Gold, intermediates one as well. In some case, if the range in grayscale is too low, the intermediate values (or values that are close but different) will have low contrast between each other... being indistinguishable...

**Comment by balacij** [comment]
Bear in mind that I don't actually know the answers to the questions I listed in the OP.

However, what you're saying sounds pretty reasonable in my opinion. A system “minimum depth” (or exact) constraint might work just as well.

**Comment by smiths** [comment]
@joedf, I agree with @balacij that you can consider your choice to document your requirements for an 8-bit grayscale as a constraint.

**Comment by joedf** [comment]
Okay, great. Thanks, will do!
